# Generated by Django 6.0.3 on 2026-04-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('medication1', models.CharField(max_length=200)),
                ('medication2', models.CharField(max_length=200)),
                ('medication3', models.CharField(max_length=200)),
            ],
        ),
    ]
