# Generated by Django 6.0.3 on 2026-04-10 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_skin_disease_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.JSONField(default=list)),
                ('predicted_disease', models.CharField(max_length=200)),
                ('confidence', models.FloatField()),
                ('top_diseases', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disease_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkinDiseaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='skin_history/')),
                ('predicted_label', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('confidence', models.FloatField()),
                ('risk_level', models.CharField(max_length=20)),
                ('top_results', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'skin_disease_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StressHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('label', models.CharField(choices=[('no_stress', 'No Stress'), ('coping', 'Coping'), ('moderate_stress', 'Moderate Stress'), ('high_stress', 'High Stress'), ('burnout', 'Burnout')], max_length=30)),
                ('label_display', models.CharField(max_length=50)),
                ('score', models.FloatField()),
                ('advice', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#94a3b8', max_length=10)),
                ('probabilities', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stress_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
    ]
